Ref/pn 9170
pagopa/pn-frontend-e2e pull request #120
Opened 2024-03-11 13:58 UTC by leleOFA

## Short description

## List of changes proposed in this pull request

- fix previous pr

## How to test

 ./mvnw clean test -Dcucumber.filter.tags=@TA_PGaccettaDelegaConGruppoConErrore

- [ ] Does this PR require a manual test in AWS CodeBuild?

2024-03-19 14:42 UTC, afus0 requested changes

2024-03-19 14:42 UTC, afus0 commented on src/test/java/it/pn/frontend/e2e/stepDefinitions/destinatario/personaGiuridica/DeleghePGPagoPATest.java
> +        deleghePGPagoPAPage.verificaEsistenzaErroreCodiceSbagliato();
You need to verify if the value inside is 'Codice di verifica non valido' and then check if the input boxes of the OTP are marked red

2024-03-19 14:42 UTC, afus0 commented on src/main/java/it/pn/frontend/e2e/pages/destinatario/personaGiuridica/DeleghePGPagoPAPage.java
> +        gruppoField.sendKeys("Errore Test");
what's the purpose of this action?

2024-03-19 14:42 UTC, afus0 commented on src/test/java/it/pn/frontend/e2e/stepDefinitions/mittente/NotificaMittentePagoPATest.java
> +
format the code and remove extra spaces

2024-03-19 14:52 UTC, leleOFA commented on src/main/java/it/pn/frontend/e2e/pages/destinatario/personaGiuridica/DeleghePGPagoPAPage.java
> +        gruppoField.sendKeys("Errore Test");
insert group and check it not exist

2024-03-19 15:04 UTC, leleOFA commented on src/test/java/it/pn/frontend/e2e/stepDefinitions/mittente/NotificaMittentePagoPATest.java
> +
delete

2024-03-19 15:04 UTC, leleOFA commented on src/test/java/it/pn/frontend/e2e/stepDefinitions/destinatario/personaGiuridica/DeleghePGPagoPATest.java
> +        deleghePGPagoPAPage.verificaEsistenzaErroreCodiceSbagliato();
done

2024-03-20 13:08 UTC, ImJimMoriarty requested changes

2024-03-20 13:08 UTC, ImJimMoriarty commented on src/test/java/it/pn/frontend/e2e/stepDefinitions/mittente/NotificaMittentePagoPATest.java
> +
```suggestion
/**
 * A simple object that represents the esito notifica, i.e. the return value of siVerificaEsitoNotifica.
 */
```

2024-03-20 13:37 UTC, leleOFA commented on src/test/java/it/pn/frontend/e2e/stepDefinitions/mittente/NotificaMittentePagoPATest.java
> +
done

2024-03-20 14:07 UTC, ImJimMoriarty approved these changes

2024-03-20 14:07 UTC, merged