Pn 9224 ScenarioA29 notifiche section - search notification by time period
pagopa/pn-frontend-e2e pull request #122
Opened 2024-03-11 15:57 UTC by Gabriiii99

## Short description

refactor 018A_ricercaPerData.feature

## List of changes proposed in this pull request

refactor method in scenarioA29

## How to test

Add a time period to search for notification, once found verify check the possibility of changing the page and then logging out

- [ x] Does this PR require a manual test in AWS CodeBuild?

2024-03-11 16:26 UTC, leleOFA commented on src/main/java/it/pn/frontend/e2e/pages/destinatario/personaFisica/NotifichePFPage.java
> +            this.getWebDriverWait(30).withMessage("Il titolo della pagina Notifiche non è visibile").until(ExpectedConditions.visibilityOf(titleLabel));
insert here wait for 10 sec

2024-03-12 10:14 UTC, ImJimMoriarty requested changes
There are some changes to make but overall it is well done. Make sure to test it locally once you done the changes.

2024-03-12 10:14 UTC, ImJimMoriarty commented on src/main/java/it/pn/frontend/e2e/pages/destinatario/personaFisica/NotifichePFPage.java
> +            paginaSeconda.click();
Check `clickPagina()` in  `PiattaformaNotifichePage.java` there is already a method that should work for every platform(pa,pf,pg)

2024-03-12 10:14 UTC, ImJimMoriarty commented on src/main/java/it/pn/frontend/e2e/pages/destinatario/personaFisica/NotifichePFPage.java
> +    public void clickPage3() {
Same here, check for `clickPagina()` in  `PiattaformaNotifichePage.java`

2024-03-12 10:14 UTC, ImJimMoriarty commented on src/main/java/it/pn/frontend/e2e/pages/destinatario/personaFisica/NotifichePFPage.java
> +            this.getWebDriverWait(20).withMessage("bottone pagina 2 non è visibile").until(ExpectedConditions.visibilityOf(paginaSeconda));
By default we usually put this **10 seconds** because it shouldn't take so much time to load a button if so there is a problem behind the scene

2024-03-12 10:14 UTC, ImJimMoriarty commented on src/main/java/it/pn/frontend/e2e/pages/destinatario/personaFisica/NotifichePFPage.java
> +        getWebDriverWait(30).withMessage("Il campo data inizio non è visibile").until(ExpectedConditions.visibilityOf(dataInizioField));
same here add **10 seconds**

2024-03-12 10:14 UTC, ImJimMoriarty commented on src/main/java/it/pn/frontend/e2e/section/destinatario/personaFisica/HeaderPFSection.java
>      WebElement profiloUtenteMenu;
If the **id** or **data-testid** aren't present find elements with `xpath` method

2024-03-12 10:14 UTC, ImJimMoriarty commented on src/main/java/it/pn/frontend/e2e/section/destinatario/personaFisica/HeaderPFSection.java
> +            this.getWebDriverWait(30).withMessage("menu dell'utente non è visibile").until(ExpectedConditions.visibilityOf(profiloUtenteMenu));
same here add **10 seconds**

2024-03-12 13:41 UTC, ImJimMoriarty approved these changes

2024-03-12 13:41 UTC, merged