PN 9163 e 2 e destinatario PG sezione stato piattaforma disservizi in corso PG
pagopa/pn-frontend-e2e pull request #135
Opened 2024-03-20 14:22 UTC by Gabriiii99

## Short description

Refactor test visualizza disservizio PG

## List of changes proposed in this pull request

Added step to control table row with Stato "in corso"
modified step for PA to match requirement for both PA and PG

## How to test

Verify the correct display of the outage information. Log in helpdesk, create an outage, verify the correct creation of it and verify the correct display of the table in stato della piattaforma PG

- [ x ] Does this PR require a manual test in AWS CodeBuild?

2024-03-21 08:27 UTC, ImJimMoriarty requested changes

2024-03-21 08:27 UTC, ImJimMoriarty commented on src/main/java/it/pn/frontend/e2e/pages/mittente/DisserviziAppPAPage.java
> +                                logger.info("Si visualizza ");
I think you forgot to add the entire log

2024-03-21 08:28 UTC, ImJimMoriarty requested changes

2024-03-21 08:28 UTC, ImJimMoriarty commented on src/main/java/it/pn/frontend/e2e/pages/mittente/DisserviziAppPAPage.java
> +                                logger.info("Si visualizza ");
I think you forgot to add the entire log

2024-03-22 15:46 UTC, afus0 requested changes
The work with the double tab is perfect! Well done. This will certainly be useful for the implementation of future tests.

2024-03-22 15:46 UTC, afus0 commented on src/test/java/it/pn/frontend/e2e/stepDefinitions/destinatario/personaGiuridica/DisserviziAppPGTest.java
> +                TimeUnit.SECONDS.sleep(1);
you can remove this because you do have 15 seconds after

2024-03-22 15:46 UTC, afus0 commented on src/test/resources/feature/3-destinatario/personaGiuridica/deleghePG/001_113_aggiuntaNuovaDelegaPG.feature
> +      | ragioneSociale | Le Epistolae srl  |
Maybe i'll suggest you to keep with the string method because you do have only 1 attribute

2024-03-22 16:18 UTC, Gabriiii99 commented
Build success on aws

2024-03-25 11:57 UTC, Gabriiii99 commented
All modified test passed on aws

2024-03-25 15:39 UTC, ImJimMoriarty approved these changes

2024-03-25 15:39 UTC, merged