ref/9162 - control on altri recapiti fields
pagopa/pn-frontend-e2e pull request #140
Opened 2024-03-26 13:17 UTC by Gabriiii99

## Short description

added check on table "GIà associati", moved a duplicated method, added new method to insert records in the table

## List of changes proposed in this pull request

- implemented steps to insert record in the table "GIà associati" and checks on the table's fields
- moved a method in the correct file
- updated a test with the correct method (from PF to PG)

## How to test

Simply run `mvn clean test -Dcucumber.filter.tags=@TA_visualizzazioneSezioneAltriRecapitiPG` and verify if the test works fine.

- [x] Does this PR require a manual test in AWS CodeBuild?

2024-03-26 13:29 UTC, Gabriiii99 commented
Build success on aws

2024-03-26 16:26 UTC, ImJimMoriarty requested changes

2024-03-26 16:26 UTC, ImJimMoriarty commented on src/main/java/it/pn/frontend/e2e/common/RecapitiDestinatarioPage.java
> +        By deleteButtonBy = By.xpath(".//button[contains(@id, 'cancelContact')]");
If there are multiple element with the same id, you can just do a specific select like so: 
`By.xpath("//div[@id='example']//div[@id='sub-example']//button[@id='real-element']")`

2024-03-26 16:26 UTC, ImJimMoriarty commented on src/main/java/it/pn/frontend/e2e/common/RecapitiDestinatarioPage.java
> +        List<WebElement> tableRows = tableGiaAssociati.findElements(By.xpath(".//tbody/tr"));
Check the previous comment and see if  you can change something

2024-03-26 16:26 UTC, ImJimMoriarty commented on src/main/java/it/pn/frontend/e2e/common/RecapitiDestinatarioPage.java
> +            List<WebElement> columns = row.findElements(By.xpath(".//td"));
Same with the above

2024-03-27 15:14 UTC, leleOFA commented on src/test/resources/feature/3-destinatario/personaGiuridica/altriRecapitiPG/008_071_visualizzazioneAltriRecapitiPG.feature
>      And Nella pagina I Tuoi Recapiti si recupera il codice OTP tramite chiamata request "personaGiuridica"
delete in line 13 yaml logic

2024-03-27 16:24 UTC, Gabriiii99 commented on src/test/resources/feature/3-destinatario/personaGiuridica/altriRecapitiPG/008_071_visualizzazioneAltriRecapitiPG.feature
>      And Nella pagina I Tuoi Recapiti si recupera il codice OTP tramite chiamata request "personaGiuridica"
16 or 13?

2024-04-03 07:01 UTC, afus0 approved these changes

2024-04-03 07:01 UTC, merged