Ref/pn 9403
pagopa/pn-frontend-e2e pull request #141
Opened 2024-03-26 14:52 UTC by leleOFA

## Short description

added cancel revoke delegation 
## List of changes proposed in this pull request

- insert missed step 
- insert click on cancel revoke button

## How to test

 ./mvnw clean test -Dcucumber.filter.tags=@TA_PFrevocaDelega    

- [ ] Does this PR require a manual test in AWS CodeBuild?

2024-03-26 16:31 UTC, ImJimMoriarty requested changes

2024-03-26 16:31 UTC, ImJimMoriarty commented on src/main/java/it/pn/frontend/e2e/pages/destinatario/personaFisica/DeleghePage.java
> +            TimeUnit.SECONDS.sleep(2);
Why the need of this wait?

2024-03-27 12:49 UTC, leleOFA commented on src/main/java/it/pn/frontend/e2e/pages/destinatario/personaFisica/DeleghePage.java
> +            TimeUnit.SECONDS.sleep(2);
because is more fast for open menu

2024-03-27 14:11 UTC, ImJimMoriarty requested changes

2024-03-27 14:11 UTC, ImJimMoriarty commented on src/main/java/it/pn/frontend/e2e/pages/destinatario/personaFisica/DeleghePage.java
>      }
```
public void clickMenuDelegato(String fullName) {
        List<WebElement> tableRows = driver.findElements(By.id("delegatesTable.body.row")); // Take all the rows of the table
        if (!tableRows.isEmpty()) {
            for (WebElement row : tableRows) {
                By cellName = By.xpath("//td//p[contains(text(), '" + fullName + "')]"); // Take the cell with the name of the delegate from the row
                getWebDriverWait(10).withMessage("Non è stato trovato la riga corrispondente della delega con il nome: " + fullName).until(ExpectedConditions.visibilityOfElementLocated(cellName));
                WebElement menuButton = row.findElement(By.xpath("//button[@data-testid='delegationMenuIcon']")); // take the menu button from the row
                getWebDriverWait(10).withMessage("Non è stato trovato il menu della delega con il nome: " + fullName).until(ExpectedConditions.visibilityOf(menuButton));
                menuButton.click();
                return;
            }
            logger.info("Cliccato correttamente su menu delega button");
        } else {
            logger.error("Non è stato trovato nessun delegato con il nome: " + fullName);
            Assert.fail("Non è stato trovato nessun delegato con il nome: " + fullName);
        }
    }
```

2024-03-27 14:11 UTC, ImJimMoriarty commented on src/test/java/it/pn/frontend/e2e/stepDefinitions/destinatario/personaFisica/DeleghePagoPATest.java
> +        deleghePage.clickMenuDelega(nome, cognome);
```
@And("Nella sezione Deleghe si clicca sul menu della delega")
    public void nellaSezioneDelegheSiCliccaSulMenuDellaDelega(Map<String, String> personaFisica) {
        logger.info("Si clicca sul menu della delega");
        String fullName = personaFisica.get("nome") + " " + personaFisica.get("cognome");
        deleghePage.clickMenuDelegato(fullName);
}
```

2024-03-27 14:55 UTC, leleOFA commented on src/test/java/it/pn/frontend/e2e/stepDefinitions/destinatario/personaFisica/DeleghePagoPATest.java
> +        deleghePage.clickMenuDelega(nome, cognome);
done

2024-03-27 15:36 UTC, ImJimMoriarty approved these changes

2024-03-27 15:36 UTC, merged