Pn 9334 e 2 e destinatario altri recapiti visualizzazione già associati PF
pagopa/pn-frontend-e2e pull request #142
Opened 2024-03-26 16:19 UTC by Gabriiii99

## Short description

added checks on table "Già associati", modified step to make it viable for both PG and PF

## List of changes proposed in this pull request

- implemented checks on the table's fields PF
- modified 9162's last step to make it viable for both PG and PF
- some method's name refactor

## How to test

Simply run `mvn clean test -Dcucumber.filter.tags=@TA_visualizzazioneSezioneAltriRecapitiPF` and verify if the test works fine.

- [x] Does this PR require a manual test in AWS CodeBuild?

2024-03-27 09:28 UTC, Gabriiii99 commented
Buil success on aws

2024-03-27 14:49 UTC, ImJimMoriarty requested changes

2024-03-27 14:49 UTC, ImJimMoriarty commented on src/main/java/it/pn/frontend/e2e/common/RecapitiDestinatarioPage.java
> +            }
what happen if you find more than 2 contact?

2024-04-10 10:06 UTC, ImJimMoriarty approved these changes

2024-04-10 10:06 UTC, merged