Test 10395
pagopa/pn-frontend-e2e pull request #179
Opened 2024-06-04 09:52 UTC by Gabriiii99

## Short description

Check download in a cancelled notification

## List of changes proposed in this pull request

- implemented a new test:
   - checks for the absence of the pay button
   - checks if the f24 and the avviso PagoPa are downloadable
- created some steps for the checks written above

## How to test

Simply run `mvn clean test -D"cucumber.filter.tags=@checkDownloadFileNotificaAnnullata"` and verify if the test works fine.

- [x] Does this PR require a manual test in AWS CodeBuild?

2024-06-04 10:03 UTC, Gabriiii99 commented
Build success on AWS

2024-06-11 14:34 UTC, afus0 requested changes

2024-06-11 14:34 UTC, afus0 commented on src/test/java/it/pn/frontend/e2e/stepDefinitions/destinatario/personaFisica/NotifichePersonaFisicaPagoPATest.java
> +            }
```suggestion
WebTool.waitTime(5);
```

2024-06-11 14:34 UTC, ImJimMoriarty commented on src/test/java/it/pn/frontend/e2e/stepDefinitions/destinatario/personaGiuridica/NotifichePGPagoPATest.java
> +        String urlChiamata = "https://webapi." + variabileAmbiente + ".notifichedigitali.it/delivery/notifications/received?";
The url has changed, check if you can use the one set in ApiBaseUrl, maybe the response is different...

2024-06-11 14:34 UTC, ImJimMoriarty commented on src/test/java/it/pn/frontend/e2e/stepDefinitions/destinatario/personaGiuridica/NotifichePGPagoPATest.java
> +            String urlChiamata = "https://webapi." + variabileAmbiente + ".notifichedigitali.it/delivery/notifications/received?";
same with what said above

2024-06-11 14:49 UTC, Gabriiii99 commented on src/test/java/it/pn/frontend/e2e/stepDefinitions/destinatario/personaFisica/NotifichePersonaFisicaPagoPATest.java
> +            }
WebTool.waitTime force a page refresh, need to verify if this can work

2024-06-11 15:12 UTC, Gabriiii99 commented
Build success on AWS

2024-06-11 15:32 UTC, ImJimMoriarty approved these changes

2024-06-11 15:33 UTC, merged